
CONDITIONS_HELP = {
	'NoCondition':'No condition.',
	'CountdownTimer':'Countdown timer is Comparison(1) Number(1) game seconds.',
	'Command':'Player(1) commands Comparison(1) Number(1) TUnit(1).',
	'Bring':'Player(1) brings Comparison(1) Number(1) TUnit(1) to Location(1).',
	'Accumulate':'Player(1) accumulates Comparison(1) Number(1) ResType(1).',
	'Kill':'Player(1) kills Comparison(1) Number(1) TUnit(1).',
	'CommandTheMost':'Current player commands the most TUnit(1).',
	'CommandsTheMostAt':'Current player commands the most TUnit(1) at Location(1).',
	'MostKills':'Current player has most kills of TUnit(1).',
	'HighestScore':'Current player has highest ScoreType(1).',
	'MostResources':'Current player has most ResType(1).',
	'Switch':'Switch(1) is Set(1).',
	'ElapsedTime':'Elapsed scenario time is Comparison(1) Number(1) game seconds.',
	'Opponents':'Player(1) has Comparison(1) Number(1) opponents remaining in the game.',
	'Deaths':'Player(1) has suffered Comparison(1) Number(1) deaths of TUnit(1).',
	'CommandTheLeast':'Current player commands the least TUnit(1).',
	'CommandTheLeastAt':'Current player commands the least TUnit(1) at Location(1).',
	'LeastKills':'Current player has least kills of TUnit(1).',
	'LowestScore':'Current player has lowest ScoreType(1).',
	'LeastResources':'Current player has least ResType(1).',
	'Score':'Player(1) ScoreType(1) score is Comparison(1) Number(1).',
	'Always':'Always.',
	'Never':'Never.',
}
ACTIONS_HELP = {
	'NoAction':'No action',
	'Victory':'End scenario in victory for current player.',
	'Defeat':'End scenario in defeat for current player.',
	'PreserveTrigger':'Preserve trigger.',
	'Wait':'Wait for Number(1) milliseconds.',
	'PauseGame':'Pause the game.',
	'UnpauseGame':'Unpause the game.',
	'Transmission':'Send transmission to current player from Unit(1) at Location(1). Play WAV(1). Modify transmission duration: Modifier(1) Number(1) milliseconds. Display String(1).',
	'PlayWAV':'Player WAV(1).',
	'DisplayTextMessage':'Display(1) String(1) for current player.',
	'CenterView':'Center view for current player at Location(1).',
	'CreateUnitWithProperties':'Create Number(1) Unit(1) at Location(1) for Player(1). Apply Property(1).',
	'SetMissionObjectives':'Set mission objectives to String(1).',
	'SetSwitch':'SwitchAction(1) Switch(1.)',
	'SetCountdownTimer':'Modify countdown timer: Modifier(1) Number(1) seconds.',
	'RunAIScript':'Execute AI Script AIScript(1).',
	'RunAIScriptAtLocation':'Execute AI Script AIScript(1) at Location(1).',
	'LeaderBoardControl':'Show Leader Board for most control of TUnit(1). Display label String(1).',
	'LeaderBoardControlAtLocation':'Show Leader Board for most control of TUnit(1) at Location(1). Display label String(1).',
	'LeaderBoardResources':'Show Leader Board for accumulation of most ResType(1). Display label String(1).',
	'LeaderBoardKills':'Show Leader Board for player closest to Number(1) kills of TUnit(1). Display label String(1).',
	'LeaderBoardPoints':'Show Leader Board for player closest to Number(1) of ScoreType(1). Display label String(1).',
	'KillUnit':'Kill all TUnit(1) for Player(1).',
	'KillUnitsAtLocation':'Kill QNumber(1) TUnit(1) for Player(1) at Location(1).',
	'RemoveUnit':'Remove all TUnit(1) for Player(1).',
	'RemoveUnitAtLocation':'Remove QNumber(1) TUnit(1) for Player(1) at Location(1).',
	'SetResources':'Modify resources for Player(1): Modifier(1) Number(1) of ResType(1).',
	'SetScore':'Modify score for Player(1): Modifier(1) Number(1) of ScoreType(1).',
	'MinimapPing':'Show minimap ping for current player at Location(1).',
	'TalkingPortrait':'Show Unit(1) talking to current player for Number(1) milliseconds.',
	'MuteUnitSpeech':'Mute all non-trigger unit sounds for current player.',
	'UnmuteUnitSpeech':'Unmute all non-trigger unit sounds for current player.',
	'LeaderboardComputerPlayers':'Set use of computer players in leaderboard calculations to State(1).',
	'LeaderboardGoalControl':'Show Leader Board for player closest to control of Number(1) of TUnit(1). Display label String(1).',
	'LeaderboardGoalControlAtLocation':'Show Leader Board for player closest to control of Number(1) of TUnit(1) at Location(1). Display label String(1).',
	'LeaderboardGoalResources':'Show Leader Board for player closest to accumulation of Number(1) ResType(1). Display label String(1)',
	'LeaderboardGoalKills':'Show Leader Board for player closest to Number(1) kills of TUnit(1). Display label String(1).',
	'LeaderboardGoalPoints':'Show Leader Board for player closest to Number(1) of ScoreType(1). Display label String(1).',
	'MoveLocation':'Center location DestLocation(1) on TUnit(1) owned by Player(1) at Location(1).',
	'MoveUnit':'Move QNumber(1) Unit(1) for Player(1) at Location(1) to DestLocation(1).',
	'LeaderboardGreed':'Show Greed Leader Board for player closest to accumulation of Number(1) ore and gas.',
	'SetNextScenario':'Load scenario String(1) after completion of current game.',
	'SetDoodadState':'Set doodad state for Unit(1) for Player(1) at Location(1) to State(1).',
	'SetInvincibility':'Set invincibility for Unit(1) owned by Player(1) at Location(1) to State(1).',
	'CreateUnit':'Create Number(1) Unit(1) at Location(1) for Player(1).',
	'SetDeaths':'Modify death counts for Player(1): Modifier(1) Number(1) for Unit(1).',
	'Order':'Issue order to all TUnit(1) owned by Player(1) at Location(1): Order(1) to DestLocation(1).',
	'Comment':'Comment: String(1).',
	'GiveUnitstoPlayer':'Give QNumber(1) TUnit(1) owned by Player(1) at Location(1) to DestPlayer(1).',
	'ModifyUnitHitPoints':'Set hit points for QNumber(1) TUnit(1) owned by Player(1) at Location(1) to Percentage(1).',
	'ModifyUnitEnergy':'Set energy points for QNumber(1) TUnit(1) owned by Player(1) at Location(1) to Percentage(1).',
	'ModifyUnitShieldPoints':'Set shield points for QNumber(1) Unit(1) owned by Player(1) at Location(1) to Percentage(1)',
	'ModifyUnitResourceAmount':'Set resource amount for QNumber(1) resource sources owned by Player(1) at Location(1) to Number(1).',
	'ModifyUnitHangerCount':'Add at most Number(1) to hangar for QNumber(1) TUnit(1) at Location(1) owned by Player(1).',
	'PauseTimer':'Pause the countdown timer.',
	'UnpauseTimer':'Unpause the countdown timer.',
	'Draw':'End the scenario in a draw for all players.',
	'SetAllianceStatus':'Set Player(1) to AllyStatus(1).',
	'DisableDebugMode':'Disable debug mode (does nothing?).',
	'EnableDebugMode':'Enable debug mode (does nothing?).',
}
NEW_ACTIONS_HELP = {
	'SetMemoryLocation':'Modify MemoryLocation(1): Modifier(1) NewValue(1).',
	'SetDuoMemoryLocation':'Modify MemoryLocationEnd(1): Modifier(1) MemoryLocation(1)',
	'SetLocationTo':'Modify LocationProps(1) for Location(1): Top left corner to (NewX1,NewY1) and top right corner to (NewX2,NewY2) and elevations LocationFlags(1).',
	'SetLocationFromDeath':'Modifier(1) LocationProps(1) for Location(1) from deaths of Unit(1) owned by Player(1).',
	'DCMath':'Do Math(1) to death count of DestUnit(1) owned by DestPlayer(1) with death count of Unit(1) owned by Player(1).',
	'DisplayStatTxtString':'Display stat_txt.tbl string StringID(1).',
	'SetGameSpeed':'Set game speed to Speed(1) Multiplier(1).',
	'SetSupplyValue':'Modify SupplyType(1) for Player(1): Modifier(1) NewValue(1).',
	'SendUnitOrder':'Modify order of TUnit(1) owned by Player(1) in Location(1) to OrderID(1).',
	'SetUnitTargetToUnit':'Modify order target of TUnit(1) owned by Player(1) in Location(1) to TUnitEnd(1) owned by PlayerEnd(1) in EndLocation(1).',
	'SetUnitTargetToLocation':'Modify order target of TUnit(1) owned by Player(1) in Location(1) to EndLocation(1).',
	'SetUnitTargetToCoords':'Modify order target of TUnit(1) owned by Player(1) in Location(1) to (NewX,NewY).',
	'SetUnitHP':'Modify hit points of TUnit(1) owned by Player(1) in Location(1): Modifier(1) Number(1)',
	'SetUnitShields':'Modify shield points of TUnit(1) owned by Player(1) in Location(1): Modifier(1) Number(1)',
	'SetPlayerVision':'Set Player(1) vision of PlayerEnd(1) to Vision(1)',
}
